version: '3.8'
services: 
  elasticsearch:
    image: elasticsearch:7.12.0
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - es_test_data:/usr/share/elasticsearch/data
      - es_plugins_data:/usr/share/elasticsearch/plugins
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms84m -Xmx512m"
      TZ: Asia/Shanghai
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456

volumes:
  es_test_data:
  es_plugins_data: